#!/usr/bin/env bash
# Generated by generate_td1601_makefiles.py.
# Copy a macOS-local firmware into the Samba-shared ISP project, then burn it
# from Ubuntu. This script can be launched from any macOS working directory.
#
# Usage:
#   ./utilities/macos-copy-and-download.sh /dev/ttyUSB0 /path/to/firmware.bin

set -euo pipefail

PROJECT_DIR="${PROJECT_DIR:-/Volumes/mpushare/mpushare/macos_workspace/isp-9star}"
REMOTE_DOWNLOADER="${REMOTE_DOWNLOADER:-${PROJECT_DIR}/isp-remote-download.sh}"
if (( $# != 2 )); then
    echo "Usage: $0 /dev/ttyUSB0 /path/to/firmware.bin" >&2
    exit 2
fi

serial_port="$1"
source_file="$2"

if [[ ! -d "$PROJECT_DIR" ]]; then
    echo "ISP project directory not found: $PROJECT_DIR" >&2
    exit 1
fi
if [[ ! -x "$REMOTE_DOWNLOADER" ]]; then
    echo "Remote downloader not found or not executable: $REMOTE_DOWNLOADER" >&2
    exit 1
fi
if [[ ! -f "$source_file" ]]; then
    echo "Firmware file not found: $source_file" >&2
    exit 1
fi

# Stage first so a failed local copy never removes the current shared firmware.
staged_file="$(mktemp "${PROJECT_DIR}/.isp-firmware.XXXXXX")"
cleanup_stage() {
    rm -f "$staged_file"
}
trap cleanup_stage EXIT
cp "$source_file" "$staged_file"

# Use the source name and pass its path explicitly to the remote downloader.
# This avoids a hard-coded firmware version and ambiguous auto-detection.
target_file="${PROJECT_DIR}/$(basename "$source_file")"
cp "$staged_file" "$target_file"
rm -f "$staged_file"
trap - EXIT

echo "Copied firmware to shared project: $target_file"
exec "$REMOTE_DOWNLOADER" "$serial_port" "$target_file"
