#!/bin/bash
# Generated by generate_td1601_makefiles.py. Run after `make`.
set -euo pipefail
PROJECT="gui"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
BOARD="$REPO/boards/td1601_evb/v1.0"
OBJ="$HERE/Obj"
ELF="$OBJ/$PROJECT.elf"
TC_DIR="${TOOLCHAIN_DIR:-$HOME/opt/xpack-riscv/xpack-riscv-none-elf-gcc-14.3.0-1}"
OBJCOPY="$TC_DIR/bin/riscv-none-elf-objcopy"
VERSION="$(sed -n 's/^version:[[:space:]]*V//p' "$HERE/package.yaml" | head -n 1 | tr -d '\r')"
ADDR="$(grep 'SPIFLASH : ORIGIN = ' "$BOARD/gcc_flash.ld" | grep -oE '0x[0-9a-fA-F]+' | head -n 1)"
[ -n "$VERSION" ] && [ -n "$ADDR" ] && [ -f "$ELF" ] || { echo 'missing ELF, version, or flash address' >&2; exit 1; }
RAW="$OBJ/${PROJECT}_${ADDR}.bin"
MNT="$OBJ/${PROJECT}_${ADDR}-mnt.bin"
OUT="$OBJ/${PROJECT}_${ADDR}_V${VERSION}.bin"
"$OBJCOPY" -O binary "$ELF" "$RAW"
offset=$((16#${ADDR#0x} - 16#18000000))
wine_bin="$(command -v wine || command -v wine64 || true)"
[ -n "$wine_bin" ] || { echo 'wine/wine64 is required for product.exe signing' >&2; exit 1; }
"$wine_bin" "$BOARD/bootimgs/product.exe" sig "$RAW" -n "$VERSION" -iver 0x58 -s "$BOARD/bootimgs/private.ecc.pem" -o "$MNT" -t SPI_Flash -a "$offset" -tr SPI_Flash -ar "$offset" -ss ECC160r1 -ds SHA1 -d
append_crc() { python3 - "$1" "$2" <<'PY'
import sys, zlib
crc = zlib.crc32(open(sys.argv[1], 'rb').read()) & 0xffffffff
open(sys.argv[2], 'ab').write(crc.to_bytes(4, 'little'))
PY
}
append_crc "$RAW" "$MNT"
dd if=/dev/zero of="$OBJ/fill.bin" bs=3988 count=1 status=none
cat "$MNT" "$OBJ/fill.bin" "$RAW" > "$OUT"
append_crc "$OUT" "$OUT"
echo "Flashable image: $OUT"
