#!/bin/bash
# Download an already-packaged firmware image with the local Windows ISP tool.
set -euo pipefail

usage() {
    printf '%s\n' \
        'Usage: build_patch_download_windows.sh -p COMx -f firmware.bin [-d BROM_DL.exe]' \
        '' \
        '  -p  Windows serial port, for example COM3.' \
        '  -f  Flashable firmware generated by aft_build_windows.sh.' \
        '  -d  Downloader path. Defaults to ../../tools/ISP/BROM_DL.exe.' \
        '  -h  Show this help.'
}

SCRIPT_DIR="${BASH_SOURCE[0]%/*}"
[ "$SCRIPT_DIR" = "${BASH_SOURCE[0]}" ] && SCRIPT_DIR="."
HERE="$(cd "$SCRIPT_DIR" && pwd)"
REPO="$(cd "$HERE/../.." && pwd)"
PORT=""
FIRMWARE=""
DOWNLOADER="$REPO/tools/ISP/BROM_DL.exe"

while getopts ":p:f:d:h" option; do
    case "$option" in
        p) PORT="$OPTARG" ;;
        f) FIRMWARE="$OPTARG" ;;
        d) DOWNLOADER="$OPTARG" ;;
        h)
            usage
            exit 0
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            usage >&2
            exit 2
            ;;
        \?)
            echo "Unknown option: -$OPTARG" >&2
            usage >&2
            exit 2
            ;;
    esac
done

[ -n "$PORT" ] || { echo "Serial port is required." >&2; usage >&2; exit 2; }
[ -n "$FIRMWARE" ] || { echo "Firmware path is required." >&2; usage >&2; exit 2; }
[ -f "$FIRMWARE" ] || { echo "Firmware was not found: $FIRMWARE" >&2; exit 1; }
[ -f "$DOWNLOADER" ] || { echo "Downloader was not found: $DOWNLOADER" >&2; exit 1; }

FIRMWARE_PARENT="${FIRMWARE%/*}"
[ "$FIRMWARE_PARENT" = "$FIRMWARE" ] && FIRMWARE_PARENT="."
FIRMWARE_ABS="$(cd "$FIRMWARE_PARENT" && pwd)/${FIRMWARE##*/}"

DOWNLOADER_PARENT="${DOWNLOADER%/*}"
[ "$DOWNLOADER_PARENT" = "$DOWNLOADER" ] && DOWNLOADER_PARENT="."
DOWNLOADER_ABS="$(cd "$DOWNLOADER_PARENT" && pwd)/${DOWNLOADER##*/}"
TOOL_DIR="${DOWNLOADER_ABS%/*}"

WIN_DOWNLOADER="$(cygpath -aw "$DOWNLOADER_ABS")"
WIN_FIRMWARE="$(cygpath -aw "$FIRMWARE_ABS")"

echo "Downloader: $WIN_DOWNLOADER"
echo "Firmware: $WIN_FIRMWARE"

pushd "$TOOL_DIR" >/dev/null
PYTHONIOENCODING=utf-8 PYTHONUTF8=1 "$WIN_DOWNLOADER" "$PORT" "$WIN_FIRMWARE"
popd >/dev/null
