#!/usr/bin/env python3
"""
jpg_to_c.py — 把 JPEG 文件转换成 C 数组源文件，编译进嵌入式固件。

用法：
    python3 utilities/jpg_to_c.py pic/1.jpg src/img_1.c

生成的 img_1.c 包含：
    extern const uint8_t  img_1_jpg[];
    extern const uint32_t img_1_jpg_len;
"""

import sys
import os


def jpg_to_c(jpg_path: str, c_path: str) -> None:
    # 读取 JPEG 原始字节
    with open(jpg_path, "rb") as f:
        data = f.read()

    # 从文件名推导 C 变量名（去路径、去扩展名、非法字符换 _）
    base = os.path.splitext(os.path.basename(jpg_path))[0]
    var_name = "".join(c if c.isalnum() else "_" for c in base)
    # C 标识符不能以数字开头
    if var_name and var_name[0].isdigit():
        var_name = "img_" + var_name
    array_name = f"{var_name}_jpg"
    len_name   = f"{var_name}_jpg_len"

    # 推导对应的头文件名
    h_name = os.path.splitext(os.path.basename(c_path))[0] + ".h"

    lines = []
    lines.append(f"/* Auto-generated by jpg_to_c.py — DO NOT EDIT */")
    lines.append(f"/* Source: {jpg_path}  ({len(data)} bytes) */")
    lines.append(f"")
    lines.append(f'#include "{h_name}"')
    lines.append(f"")
    lines.append(f"/* JPEG raw data */")
    lines.append(f"const uint8_t {array_name}[] = {{")

    # 每行 16 字节，对齐排列
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        lines.append(f"    {hex_str},")

    lines.append(f"}};")
    lines.append(f"")
    lines.append(f"const uint32_t {len_name} = {len(data)}U;")
    lines.append(f"")

    with open(c_path, "w") as f:
        f.write("\n".join(lines))

    # 同步生成 .h 声明文件
    h_path = os.path.join(os.path.dirname(c_path), h_name)
    guard = h_name.upper().replace(".", "_").replace("-", "_")
    h_lines = [
        f"/* Auto-generated by jpg_to_c.py — DO NOT EDIT */",
        f"#ifndef {guard}",
        f"#define {guard}",
        f"",
        f"#include <stdint.h>",
        f"",
        f"/* {os.path.basename(jpg_path)}: {len(data)} bytes */",
        f"extern const uint8_t  {array_name}[];",
        f"extern const uint32_t {len_name};",
        f"",
        f"#endif /* {guard} */",
        f"",
    ]
    with open(h_path, "w") as f:
        f.write("\n".join(h_lines))

    print(f"[jpg_to_c] {jpg_path} -> {c_path} + {h_path}")
    print(f"           {len(data)} bytes, array: {array_name}[]")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <input.jpg> <output.c>")
        sys.exit(1)
    jpg_to_c(sys.argv[1], sys.argv[2])
