/* Auto-generated by jpg_to_c.py — DO NOT EDIT */
#ifndef IMG_1_H
#define IMG_1_H

#include <stdint.h>

/* 1.jpg: 37956 bytes */
extern const uint8_t  img_1_jpg[];
extern const uint32_t img_1_jpg_len;

#endif /* IMG_1_H */
