#!/usr/bin/env bash
# Generated by generate_td1601_makefiles.py.
# Build, sign/package, copy to the shared ISP project, then burn over UART.
# Usage: ./build_patch_download.sh [ubuntu-serial-port]
set -euo pipefail
PROJECT="gpio_toggle"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PORT="${1:-/dev/ttyUSB0}"
# Override ISP_TOOL when the shared ISP project is mounted elsewhere.
ISP_TOOL="${ISP_TOOL:-/Volumes/mpushare/mpushare/macos_workspace/isp-9star/macos-copy-and-download.sh}"

make -C "$HERE"
"$HERE/aft_build_macos.sh"

VERSION="$(sed -n 's/^version:[[:space:]]*V//p' "$HERE/package.yaml" | head -n 1 | tr -d '\r')"
ADDR="$(grep 'SPIFLASH : ORIGIN = ' "$HERE/../../../../boards/td1601_evb/v1.0/gcc_flash.ld" | grep -oE '0x[0-9a-fA-F]+' | head -n 1)"
FIRMWARE="$HERE/Obj/${PROJECT}_${ADDR}_V${VERSION}.bin"
[ -f "$FIRMWARE" ] || { echo "firmware was not generated: $FIRMWARE" >&2; exit 1; }
[ -x "$ISP_TOOL" ] || { echo "ISP downloader not found/executable: $ISP_TOOL" >&2; exit 1; }
exec "$ISP_TOOL" "$PORT" "$FIRMWARE"
